"""initial tables

Revision ID: 196aba981137
Revises: 
Create Date: 2026-04-18 07:04:12.925740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196aba981137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', 'COGS', name='chartaccounttype', native_enum=False), nullable=False),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_account_id'], ['chart_of_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code', name='uq_chart_of_accounts_account_code')
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_account_name'), ['account_name'], unique=False)
        batch_op.create_index('ix_chart_of_accounts_account_type', ['account_type'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_cost >= 0', name='ck_items_average_cost_non_negative'),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_items_low_stock_threshold_non_negative'),
    sa.CheckConstraint('sale_price >= 0', name='ck_items_sale_price_non_negative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_items_stock_quantity_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_name'), ['supplier_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('CASH', 'BANK', name='financialaccounttype', native_enum=False), nullable=False),
    sa.Column('chart_account_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='ck_financial_accounts_current_balance_non_negative'),
    sa.CheckConstraint('opening_balance >= 0', name='ck_financial_accounts_opening_balance_non_negative'),
    sa.ForeignKeyConstraint(['chart_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    sa.UniqueConstraint('chart_account_id', name='uq_financial_accounts_chart_account_id')
    )
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_financial_accounts_account_type', ['account_type'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', name='movementtype', native_enum=False), nullable=False),
    sa.Column('reference_type', sa.Enum('PURCHASE', 'SALE', 'CUSTOMER_PAYMENT', 'SUPPLIER_PAYMENT', 'EXPENSE', 'MANUAL', name='referencetype', native_enum=False), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movements_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0 OR unit_cost IS NULL', name='ck_stock_movements_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_item_id_created_at', ['item_id', 'created_at'], unique=False)
        batch_op.create_index('ix_stock_movements_reference_type_reference_id', ['reference_type', 'reference_id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='tokentype', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name='uq_token_blocklist_jti')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index('ix_token_blocklist_user_id_expires_at', ['user_id', 'expires_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_jti', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_jti', name='uq_user_sessions_refresh_token_jti')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_user_sessions_user_id_status', ['user_id', 'status'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_category_account_id', sa.Integer(), nullable=False),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expense_category_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_expense_date', ['expense_date'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('purchase_status', sa.Enum('COMPLETED', 'CANCELLED', name='purchasestatus', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_due >= 0', name='ck_purchases_balance_due_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_purchases_discount_non_negative'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_purchases_paid_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_purchases_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_purchases_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_purchases_total_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index('ix_purchases_invoice_number', ['invoice_number'], unique=False)
        batch_op.create_index('ix_purchases_purchase_date', ['purchase_date'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('receipt_account_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('sale_status', sa.Enum('COMPLETED', 'VOIDED', name='salestatus', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_due >= 0', name='ck_sales_balance_due_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sales_discount_non_negative'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_sales_paid_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sales_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sales_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_sales_total_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_sales_invoice_number')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('ix_sales_sale_date', ['sale_date'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_customer_payments_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index('ix_customer_payments_payment_date', ['payment_date'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_purchase_items_line_total_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_items_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_purchase_items_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_sale_items_line_total_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('unit_cost_snapshot >= 0', name='ck_sale_items_unit_cost_snapshot_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payments_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_payments_payment_date', ['payment_date'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.Enum('PURCHASE', 'SALE', 'CUSTOMER_PAYMENT', 'SUPPLIER_PAYMENT', 'EXPENSE', 'MANUAL', name='referencetype', native_enum=False), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('customer_payment_id', sa.Integer(), nullable=True),
    sa.Column('supplier_payment_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_payment_id'], ['customer_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_journal_entries_entry_date', ['entry_date'], unique=False)
        batch_op.create_index('ix_journal_entries_reference_type_reference_id', ['reference_type', 'reference_id'], unique=False)

    op.create_table('journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('line_description', sa.Text(), nullable=True),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name='ck_journal_entry_lines_single_sided_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.create_index('ix_journal_entry_lines_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_journal_entry_lines_journal_entry_id', ['journal_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entry_lines_journal_entry_id')
        batch_op.drop_index('ix_journal_entry_lines_account_id')

    op.drop_table('journal_entry_lines')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entries_reference_type_reference_id')
        batch_op.drop_index('ix_journal_entries_entry_date')

    op.drop_table('journal_entries')
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_payments_payment_date')

    op.drop_table('supplier_payments')
    op.drop_table('sale_items')
    op.drop_table('purchase_items')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_payments_payment_date')

    op.drop_table('customer_payments')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_sale_date')

    op.drop_table('sales')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index('ix_purchases_purchase_date')
        batch_op.drop_index('ix_purchases_invoice_number')

    op.drop_table('purchases')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_expense_date')

    op.drop_table('expenses')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_id_status')

    op.drop_table('user_sessions')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index('ix_token_blocklist_user_id_expires_at')

    op.drop_table('token_blocklist')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_reference_type_reference_id')
        batch_op.drop_index('ix_stock_movements_item_id_created_at')

    op.drop_table('stock_movements')
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_accounts_account_type')

    op.drop_table('financial_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_name'))

    op.drop_table('suppliers')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_category'))

    op.drop_table('items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))

    op.drop_table('customers')
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_of_accounts_account_type')
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_account_name'))

    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
